- name: Install Maven
  apt:
    name: maven
    state: present
    update_cache: yes

- name: Remove Jdk
  apt:
    name: openjdk-11-jre-headless
    state: absent
    update_cache: yes

- name: Install jdk
  apt:
    name: openjdk-8-jre-headless
    state: present
    update_cache: yes

- name: Download Artifacts from Nexus
  include_tasks: download-nexus-artifacts.yml

- name: Setup SystemD Service
  include_tasks: setup-systemd.yml

- name: Install Node Exporter Prometheus Monitoring
  include_role:
    name: common
    tasks_from: node_exporter

#- name: Install Filebeat Monitoring
 #  name: common
  #  tasks_from: filebeat
  #vars:
   # IS_STRUCTURED: false
    #IS_JAVA: true
    #LOG_FILES:
     # - { file: "/var/log/{{COMPONENT}}.log", type: "{{COMPONENT}}" } 